language: node_js
deploy:
  api_key:
    secure: UCiZmuoAqKHDM8PT5KJdr92iWHmQ5nCnqPLHLIPKQn8EFQAiTl4CGMmQwMCWF+JRfYzuWPS1RbNm3r0QRpHupsTyGvUtXYLheNJAne/4lGjHi4OECI2ldRI0fTMX4MjV5h8I0Qx9gr4NHSzWIuXKWgFEdljijAmc3BwjPB3J7Aft5G4cXfSccwd70SzuT49NLOGW1OK9fFHjcuoVHq0Eb+25DCDhM2b+YwZqPe5gcgAHS9C8PgvkqNgl1/VqJJiDStnZH5CFRtrc5mhgINXRv/vnIFj6j0sYaqS+tvlM9eNyRC+lG6A518E64f92XBFkzIjvB2NQK/zhIGGE98yn1NGjsfWAWF/Mnznp0s5Og8a0yXpV9P9KowTD4ps2+1xYXN8zy2guYwS5WHjgI75Orw1u3XTs1pHLtH4XmdiFGh1JWP2R+1IiNH+B5KzqDreypkb4OVtPRl3Qvo3qkkmkJ+sXnAHsKUEDr8+EJ4StFHABySAM6z5I5RcX9pfzJ3P5KvZR5ZsdnzWZC7/yHwxspdaXMEJ76uIEP1gBigcr4A3afFFgQpAL5TVuBlNG6Q9O9b5RfmTmGdZ7wjdAXs8uA9hqpyaktbRIKdPLTbzOdHuQ+GltTpu1rbANiyvp8ahQoHRVrjxgydM5bLP8C3c+4PMuvh2d4fZgRxt5HRFJkDE=
  email: jeanfrancois.allaire@gmail.com
  provider: npm
  on:
    tags: true
